### ISSUE TITLE
Loading dictionary stored as .npz fails

### ISSUE THREAD

**Issue by NightFury13** [htwaijry/npy4th#7]
I store a dict (python) using Numpy as follows : 

```
a = {'asd':[1,2,3], 'as':[1,2], 'd':1}
np.savez('temp',a)
```

However, on trying to load the file in torch, I get the following error : 

```
th> npy4th = require 'npy4th'
                                                                      [0.0950s] 
th> arr = npy4th.loadnpz('temp.npz')
array type unsupported[string "arr = npy4th.loadnpz('temp.npz')"]:1: unsupported data type at /users/mohit.jain/torch/npy4th/npy4th.cpp:122
stack traceback:
    [C]: in function 'loadnpz'
    [string "arr = npy4th.loadnpz('temp.npz')"]:1: in main chunk
    [C]: in function 'xpcall'
    ...rs/mohit.jain/torch/install/share/lua/5.1/trepl/init.lua:669: in function 'repl'
    ...jain/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:199: in main chunk
    [C]: at 0x00406670

```

Is there something wrong with what I am doing or is this a bug?

**Comment by htwaijry** [comment]
The issue is that you are storing the dictionary object with "np.savez".
When you load this with "np.load", you will find the following:

```
>>> b=np.load('temp.npz')
>>> b.keys()
['arr_0']
>>> b['arr_0']
array({'as': array([ 1.,  2.], dtype=float32), 'd': array([ 1.], dtype=float32), 'asd': array([ 1.,  2.,  3.], dtype=float32)}, dtype=object)
```

You end up having the dictionary stored as an array of type "object", and currently npy4th right now has no way of dealing with object types.

Save your npz file as follows:

```
>>> a=  {'asd':[1,2,3], 'as':[1,2], 'd':[1]}
>>> np.savez('temp', **a)
```

Notice that for 'd'=[1], I specified the value inside a list, which would cause to get converted into a numpy array or size 1, so it can be read correctly.
Also, you need to unpack the dictionary with **, when you pass it to "np.savez"

```
th> npy4th.loadnpz('temp.npz')
{
  d : LongTensor - size: 1
  asd : LongTensor - size: 3
  as : LongTensor - size: 2
}
```

**Comment by NightFury13** [comment]
Makes sense. Thank you! :)
